### ISSUE TITLE
Write some wire format test

### ISSUE THREAD

**Issue by picnoir** [nix-community/nsncd#3]
We should interactively use the `nscd` NixOS VM test to dump some nscd responses from common operations and compare those with the responses serialized by `nsncd`.

See https://github.com/NinjaTrappeur/nsncd/commit/2a88241f1b9c0ad26951fb7d2744922607662aa0#diff-148e623ad4cdaab49b81901460099f4efe7900e8c57e4f7a0ff6778589be01f8R412 as a test example.

**Comment by flokli** [comment]
Shelving, if we do this, we'd probably send it upstream directly.
