### ISSUE TITLE
INITGROUPS fails on GIDs > 2147483647

### ISSUE THREAD

**Issue by max-privatevoid** [nix-community/nsncd#6]
User `max` is member of a group with GID 2709991565.
Running `id max`, `nsncd` (unstable-2022-11-14 from nixpkgs `96f8f4a038a190f7511da79ef7e77bec5e4b811a`) returns:
```
uid=646000001(max) gid=646000001(max) groups=646000001
```

`nscd` returns:
```
uid=646000001(max) gid=646000001(max) groups=646000001(max),2709991565(infra_admins)
```

Log for `nsncd` shows this error message:
```
Jun 11 00:00:39.334 ERRO error handling request, err: out of range integral type conversion attempted, request_type: INITGROUPS, thread: worker_5
```
Users with GIDs <= 2147483647 get their groups listed correctly, so I'm guessing this is a signed vs. unsigned issue.

**Comment by flokli** [comment]
This is a fork of https://github.com/twosigma/nsncd (with the intention to upstream), and doesn't have any changes regarding initgroups. Please open the issue [there](https://github.com/twosigma/nsncd/issues).
