### ISSUE TITLE
Error and shutdown when trying to resolve unresolvable hosts

### ISSUE THREAD

**Issue by wose** [nix-community/nsncd#7]
I have some application which maintains a list of hosts by their mdns name. Some of those hosts may be offline at any given time and therefore cannot be resolved. I'm on NixOS which now uses `nsncd`.

When there are around 10 or more hosts offline and the application tries to resolve their names `nsncd` stops with the following message:
```
Jul 13 09:25:54 xxxxxx nsncd[640]: Jul 13 09:25:54.513 ERRO timed out waiting for an available worker, thread: accept
Jul 13 09:25:54 xxxxxx nsncd[640]: Jul 13 09:25:54.513 INFO shutting down
```

As a workaround I disabled `nsncd` since `nscd` doesn't show this behaviour.

**Comment by flokli** [comment]
avahi has some quite annoyingly long timeouts - not sure what's the best way to handle this.

Can you open an issue [upstream](https://github.com/twosigma/nsncd/)? All host-related lookup functionality got merged there.
